# Generated by Django 2.2.5 on 2019-09-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrapMapApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crapmapapp',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
