# Generated by Django 2.2.5 on 2019-09-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrapMapApp', '0003_personalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='crapmapapp',
            name='subtitle',
            field=models.CharField(blank=True, default='default subtitle', max_length=200),
        ),
    ]
